// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// An ICU4X compact decimal formatter — renders a [Decimal] in
/// CLDR compact notation ("1.2M" short, "1.2 million" long).
/// ECMA-402 `notation: "compact"` with `compactDisplay` chosen at
/// construction.
///
/// See the [Rust documentation for `CompactDecimalFormatter`](https://docs.rs/icu/2.2.0/icu/decimal/struct.CompactDecimalFormatter.html) for more information.
final class CompactDecimalFormatter implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  CompactDecimalFormatter._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_CompactDecimalFormatter_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_CompactDecimalFormatter_destroy_mv1));

  /// Creates a short-form ("1.2M") compact formatter from compiled
  /// CLDR data. `grouping_strategy` defaults to the compact
  /// formatter's own default (Min2) when not given.
  ///
  /// See the [Rust documentation for `try_new_short`](https://docs.rs/icu/2.2.0/icu/decimal/struct.CompactDecimalFormatter.html#method.try_new_short) for more information.
  ///
  /// Throws [DataError] on failure.
  factory CompactDecimalFormatter.short(Locale locale, [DecimalGroupingStrategy? groupingStrategy]) {
    final result = _icu4x_CompactDecimalFormatter_create_short_mv1(locale._ffi, groupingStrategy != null ? _ResultInt32Void.ok(groupingStrategy.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return CompactDecimalFormatter._fromFfi(result.union.ok, []);
  }

  /// Creates a long-form ("1.2 million") compact formatter from
  /// compiled CLDR data.
  ///
  /// See the [Rust documentation for `try_new_long`](https://docs.rs/icu/2.2.0/icu/decimal/struct.CompactDecimalFormatter.html#method.try_new_long) for more information.
  ///
  /// Throws [DataError] on failure.
  factory CompactDecimalFormatter.long(Locale locale, [DecimalGroupingStrategy? groupingStrategy]) {
    final result = _icu4x_CompactDecimalFormatter_create_long_mv1(locale._ffi, groupingStrategy != null ? _ResultInt32Void.ok(groupingStrategy.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return CompactDecimalFormatter._fromFfi(result.union.ok, []);
  }

  ///
  ///
  /// Throws [DataError] on failure.
  factory CompactDecimalFormatter.shortWithProvider(DataProvider provider, Locale locale, [DecimalGroupingStrategy? groupingStrategy]) {
    final result = _icu4x_CompactDecimalFormatter_create_short_with_provider_mv1(provider._ffi, locale._ffi, groupingStrategy != null ? _ResultInt32Void.ok(groupingStrategy.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return CompactDecimalFormatter._fromFfi(result.union.ok, []);
  }

  ///
  ///
  /// Throws [DataError] on failure.
  factory CompactDecimalFormatter.longWithProvider(DataProvider provider, Locale locale, [DecimalGroupingStrategy? groupingStrategy]) {
    final result = _icu4x_CompactDecimalFormatter_create_long_with_provider_mv1(provider._ffi, locale._ffi, groupingStrategy != null ? _ResultInt32Void.ok(groupingStrategy.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return CompactDecimalFormatter._fromFfi(result.union.ok, []);
  }

  /// Format `value` in compact notation. The formatter applies CLDR
  /// compact rounding to the significand internally.
  ///
  /// See the [Rust documentation for `format`](https://docs.rs/icu/2.2.0/icu/decimal/struct.CompactDecimalFormatter.html#method.format) for more information.
  String format(Decimal value) {
    final write = _Write();
    _icu4x_CompactDecimalFormatter_format_mv1(_ffi, value._ffi, write._ffi);
    return write.finalize();
  }

  /// Format `value` into typed parts (ECMA-402 `formatToParts`
  /// shape): the number as integer / decimal / fraction, the
  /// abbreviation as a `compact` part.
  FormattedNumberParts formatToParts(Decimal value) {
    final result = _icu4x_CompactDecimalFormatter_format_to_parts_mv1(_ffi, value._ffi);
    return FormattedNumberParts._fromFfi(result, []);
  }

}

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_CompactDecimalFormatter_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_create_short_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_create_short_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_CompactDecimalFormatter_create_short_mv1(ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void groupingStrategy);

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_create_long_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_create_long_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_CompactDecimalFormatter_create_long_mv1(ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void groupingStrategy);

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_create_short_with_provider_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_create_short_with_provider_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_CompactDecimalFormatter_create_short_with_provider_mv1(ffi.Pointer<ffi.Opaque> provider, ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void groupingStrategy);

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_create_long_with_provider_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_create_long_with_provider_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_CompactDecimalFormatter_create_long_with_provider_mv1(ffi.Pointer<ffi.Opaque> provider, ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void groupingStrategy);

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_format_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_format_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_CompactDecimalFormatter_format_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> value, ffi.Pointer<ffi.Opaque> write);

@_DiplomatFfiUse('icu4x_CompactDecimalFormatter_format_to_parts_mv1')
@ffi.Native<ffi.Pointer<ffi.Opaque> Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_CompactDecimalFormatter_format_to_parts_mv1')
// ignore: non_constant_identifier_names
external ffi.Pointer<ffi.Opaque> _icu4x_CompactDecimalFormatter_format_to_parts_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> value);

// dart format on
