// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Width controlling the symbol form for [CurrencyFormatter].
/// Mirrors `icu_experimental::dimension::currency::options::Width`.
///
/// See the [Rust documentation for `Width`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/options/enum.Width.html) for more information.
enum CurrencyWidth {
  // ignore: public_member_api_docs
  short,
  // ignore: public_member_api_docs
  narrow;

}

// dart format on
