// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// An ICU4X currency formatter object that renders a [Decimal] with a
/// short or narrow currency symbol (e.g. "$1.00" or "US$1").
///
/// For long-form ("1 US dollar") use [LongCurrencyFormatter].
///
/// See the [Rust documentation for `CurrencyFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html) for more information.
final class CurrencyFormatter implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  CurrencyFormatter._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_CurrencyFormatter_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_CurrencyFormatter_destroy_mv1));

  /// Creates a new [CurrencyFormatter] using compiled CLDR data.
  ///
  /// Returns an error if the locale has no currency data.
  ///
  /// See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html#method.try_new) for more information.
  ///
  /// Throws [DataError] on failure.
  factory CurrencyFormatter.withWidth(Locale locale, [CurrencyWidth? width]) {
    final result = _icu4x_CurrencyFormatter_create_with_width_mv1(locale._ffi, width != null ? _ResultInt32Void.ok(width.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return CurrencyFormatter._fromFfi(result.union.ok, []);
  }

  ///
  ///
  /// Throws [DataError] on failure.
  factory CurrencyFormatter.withWidthWithProvider(DataProvider provider, Locale locale, [CurrencyWidth? width]) {
    final result = _icu4x_CurrencyFormatter_create_with_width_with_provider_mv1(provider._ffi, locale._ffi, width != null ? _ResultInt32Void.ok(width.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return CurrencyFormatter._fromFfi(result.union.ok, []);
  }

  /// Format `value` with `currency_code` (3-letter ISO 4217, e.g. "USD").
  ///
  /// Returns an empty string if `currency_code` is not a valid 3-letter
  /// ASCII code; callers should validate first.
  ///
  /// See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html#method.format_fixed_decimal) for more information.
  String format(Decimal value, String currencyCode) {
    final temp = _FinalizedArena();
    final write = _Write();
    _icu4x_CurrencyFormatter_format_mv1(_ffi, value._ffi, currencyCode._utf8AllocIn(temp.arena), write._ffi);
    return write.finalize();
  }

}

@_DiplomatFfiUse('icu4x_CurrencyFormatter_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_CurrencyFormatter_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_CurrencyFormatter_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_CurrencyFormatter_create_with_width_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_CurrencyFormatter_create_with_width_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_CurrencyFormatter_create_with_width_mv1(ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void width);

@_DiplomatFfiUse('icu4x_CurrencyFormatter_create_with_width_with_provider_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_CurrencyFormatter_create_with_width_with_provider_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_CurrencyFormatter_create_with_width_with_provider_mv1(ffi.Pointer<ffi.Opaque> provider, ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void width);

@_DiplomatFfiUse('icu4x_CurrencyFormatter_format_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, _SliceUtf8, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_CurrencyFormatter_format_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_CurrencyFormatter_format_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> value, _SliceUtf8 currencyCode, ffi.Pointer<ffi.Opaque> write);

// dart format on
