// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// A formatted number decomposed into typed parts, mirroring ECMA-402
/// `Intl.NumberFormat.prototype.formatToParts`.
///
/// Each part is a `(type, value)` pair; the types are the ECMA-402 names
/// (`"integer"`, `"group"`, `"decimal"`, `"fraction"`, `"minusSign"`,
/// `"plusSign"`, `"percentSign"`, `"currency"`, `"unit"`, `"literal"`, …).
/// Concatenating every part's value reproduces the flat formatted string.
final class FormattedNumberParts implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  FormattedNumberParts._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_FormattedNumberParts_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_FormattedNumberParts_destroy_mv1));

  /// The number of parts.
  int get partCount {
    final result = _icu4x_FormattedNumberParts_part_count_mv1(_ffi);
    return result;
  }

  /// The ECMA-402 type name of the part at `index`, or nothing if the
  /// index is out of bounds.
  String? partTypeAt(int index) {
    final write = _Write();
    final result = _icu4x_FormattedNumberParts_part_type_at_mv1(_ffi, index, write._ffi);
    if (!result.isOk) {
      return null;
    }
    return write.finalize();
  }

  /// The substring of the part at `index`, or nothing if the index is
  /// out of bounds.
  String? partValueAt(int index) {
    final write = _Write();
    final result = _icu4x_FormattedNumberParts_part_value_at_mv1(_ffi, index, write._ffi);
    if (!result.isOk) {
      return null;
    }
    return write.finalize();
  }

}

@_DiplomatFfiUse('icu4x_FormattedNumberParts_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_FormattedNumberParts_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_FormattedNumberParts_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_FormattedNumberParts_part_count_mv1')
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_FormattedNumberParts_part_count_mv1')
// ignore: non_constant_identifier_names
external int _icu4x_FormattedNumberParts_part_count_mv1(ffi.Pointer<ffi.Opaque> self);

@_DiplomatFfiUse('icu4x_FormattedNumberParts_part_type_at_mv1')
@ffi.Native<_ResultVoidVoid Function(ffi.Pointer<ffi.Opaque>, ffi.Size, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_FormattedNumberParts_part_type_at_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidVoid _icu4x_FormattedNumberParts_part_type_at_mv1(ffi.Pointer<ffi.Opaque> self, int index, ffi.Pointer<ffi.Opaque> write);

@_DiplomatFfiUse('icu4x_FormattedNumberParts_part_value_at_mv1')
@ffi.Native<_ResultVoidVoid Function(ffi.Pointer<ffi.Opaque>, ffi.Size, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_FormattedNumberParts_part_value_at_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidVoid _icu4x_FormattedNumberParts_part_value_at_mv1(ffi.Pointer<ffi.Opaque> self, int index, ffi.Pointer<ffi.Opaque> write);

// dart format on
