// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// An ICU4X long-form currency formatter pinned to one currency
/// (e.g. "1 US dollar" / "2 US dollars" with locale-aware plural form).
///
/// See the [Rust documentation for `LongCurrencyFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html) for more information.
final class LongCurrencyFormatter implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  LongCurrencyFormatter._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_LongCurrencyFormatter_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_LongCurrencyFormatter_destroy_mv1));

  /// Creates a new [LongCurrencyFormatter] for one currency using
  /// compiled CLDR data.
  ///
  /// Returns `Err(DataError)` if the locale or currency has no data.
  ///
  /// See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html#method.try_new) for more information.
  ///
  /// Throws [DataError] on failure.
  factory LongCurrencyFormatter.forCurrency(Locale locale, String currencyCode) {
    final temp = _FinalizedArena();
    final result = _icu4x_LongCurrencyFormatter_create_for_currency_mv1(locale._ffi, currencyCode._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return LongCurrencyFormatter._fromFfi(result.union.ok, []);
  }

  ///
  ///
  /// Throws [DataError] on failure.
  factory LongCurrencyFormatter.forCurrencyWithProvider(DataProvider provider, Locale locale, String currencyCode) {
    final temp = _FinalizedArena();
    final result = _icu4x_LongCurrencyFormatter_create_for_currency_with_provider_mv1(provider._ffi, locale._ffi, currencyCode._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return LongCurrencyFormatter._fromFfi(result.union.ok, []);
  }

  /// Format `value` using the locale-specific plural form
  /// (e.g. "1 US dollar" / "2 US dollars").
  ///
  /// See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html#method.format_fixed_decimal) for more information.
  String format(Decimal value) {
    final write = _Write();
    _icu4x_LongCurrencyFormatter_format_mv1(_ffi, value._ffi, write._ffi);
    return write.finalize();
  }

}

@_DiplomatFfiUse('icu4x_LongCurrencyFormatter_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_LongCurrencyFormatter_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_LongCurrencyFormatter_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_LongCurrencyFormatter_create_for_currency_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, _SliceUtf8)>(isLeaf: true, symbol: 'icu4x_LongCurrencyFormatter_create_for_currency_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_LongCurrencyFormatter_create_for_currency_mv1(ffi.Pointer<ffi.Opaque> locale, _SliceUtf8 currencyCode);

@_DiplomatFfiUse('icu4x_LongCurrencyFormatter_create_for_currency_with_provider_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, _SliceUtf8)>(isLeaf: true, symbol: 'icu4x_LongCurrencyFormatter_create_for_currency_with_provider_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_LongCurrencyFormatter_create_for_currency_with_provider_mv1(ffi.Pointer<ffi.Opaque> provider, ffi.Pointer<ffi.Opaque> locale, _SliceUtf8 currencyCode);

@_DiplomatFfiUse('icu4x_LongCurrencyFormatter_format_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_LongCurrencyFormatter_format_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_LongCurrencyFormatter_format_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> value, ffi.Pointer<ffi.Opaque> write);

// dart format on
