// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// An ICU4X percent formatter object that renders a [Decimal] with the
/// locale's percent sign (e.g. "12.34%" in en-US, "12,34 %" in fr).
///
/// See the [Rust documentation for `PercentFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/percent/formatter/struct.PercentFormatter.html) for more information.
final class PercentFormatter implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  PercentFormatter._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _finalizer.attach(this, _ffi.cast());
    }
  }

  @_DiplomatFfiUse('icu4x_PercentFormatter_destroy_mv1')
  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_icu4x_PercentFormatter_destroy_mv1));

  /// Creates a new [PercentFormatter] using compiled CLDR data.
  ///
  /// Returns an error if the locale has no percent data.
  ///
  /// See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/percent/formatter/struct.PercentFormatter.html#method.try_new) for more information.
  ///
  /// Throws [DataError] on failure.
  factory PercentFormatter.withDisplay(Locale locale, [PercentDisplay? display]) {
    final result = _icu4x_PercentFormatter_create_with_display_mv1(locale._ffi, display != null ? _ResultInt32Void.ok(display.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return PercentFormatter._fromFfi(result.union.ok, []);
  }

  ///
  ///
  /// Throws [DataError] on failure.
  factory PercentFormatter.withDisplayWithProvider(DataProvider provider, Locale locale, [PercentDisplay? display]) {
    final result = _icu4x_PercentFormatter_create_with_display_with_provider_mv1(provider._ffi, locale._ffi, display != null ? _ResultInt32Void.ok(display.index) : _ResultInt32Void.err());
    if (!result.isOk) {
      throw DataError.values[result.union.err];
    }
    return PercentFormatter._fromFfi(result.union.ok, []);
  }

  /// Format `value` as a percent. The decimal is interpreted as already
  /// scaled (i.e. `0.12` → "0.12%", not "12%"). Pre-multiply by 100 in
  /// Dart if you want ECMA-402 percent semantics ("12%" from `0.12`).
  ///
  /// See the [Rust documentation for `format`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/percent/formatter/struct.PercentFormatter.html#method.format) for more information.
  String format(Decimal value) {
    final write = _Write();
    _icu4x_PercentFormatter_format_mv1(_ffi, value._ffi, write._ffi);
    return write.finalize();
  }

}

@_DiplomatFfiUse('icu4x_PercentFormatter_destroy_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'icu4x_PercentFormatter_destroy_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_PercentFormatter_destroy_mv1(ffi.Pointer<ffi.Void> self);

@_DiplomatFfiUse('icu4x_PercentFormatter_create_with_display_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_PercentFormatter_create_with_display_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_PercentFormatter_create_with_display_mv1(ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void display);

@_DiplomatFfiUse('icu4x_PercentFormatter_create_with_display_with_provider_mv1')
@ffi.Native<_ResultOpaqueInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, _ResultInt32Void)>(isLeaf: true, symbol: 'icu4x_PercentFormatter_create_with_display_with_provider_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _icu4x_PercentFormatter_create_with_display_with_provider_mv1(ffi.Pointer<ffi.Opaque> provider, ffi.Pointer<ffi.Opaque> locale, _ResultInt32Void display);

@_DiplomatFfiUse('icu4x_PercentFormatter_format_mv1')
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'icu4x_PercentFormatter_format_mv1')
// ignore: non_constant_identifier_names
external void _icu4x_PercentFormatter_format_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> value, ffi.Pointer<ffi.Opaque> write);

// dart format on
