// Build hook for icu_kit.
//
// ═══════════════════════════════════════════════════════════════════
// STRUCTURE
// ═══════════════════════════════════════════════════════════════════
//
//   main()           Flutter/Dart hook entry point (native targets only).
//                    Resolves the binary, registers it with the build.
//
//   resolveWeb()     Public API for bin/setup.dart (web assets).
//                    Same waterfall for the WASM binary, plus a plain
//                    copy of the committed Diplomat JS bindings — the
//                    browser serves web/ as static files, no
//                    registration needed.
//
//   _resolveNative() Private. Only main() calls this — the correct
//                    cache path and target config only exist inside
//                    the build hook. setup <native> delegates to
//                    `flutter build` which triggers main().
//
// ═══════════════════════════════════════════════════════════════════
// RESOLUTION WATERFALL (same for native and web)
// ═══════════════════════════════════════════════════════════════════
//
//   1. CACHED    — existing file, only with a PROOF: hash match, or
//                  no-hash-AND-no-sources (nothing better exists).
//                  When vendor sources are present and there is no
//                  hash, this step always falls through — freshness
//                  is cargo's question, never file-existence.
//   2. DOWNLOAD  — fetch from GitHub Releases; verified against the
//                  pinned hash at download time (or used with a loud
//                  warning when neither hash nor source exists) → cache
//   3. COMPILE   — vendor/icu4x/ exists → cargo → use it
//   4. SUBMODULE — .gitmodules exists → git init recursive → compile
//   5. ERROR     — nothing worked, clear message with options
//
//   --force skips step 1 (web only, via setup.dart).
//   Version 0.0.0 (dev) skips step 2 (no release exists) — so every
//   dev build lands on step 3 and cargo's fingerprint check decides
//   whether anything actually recompiles (~1s when nothing changed).
//
// ═══════════════════════════════════════════════════════════════════
// USER SCENARIOS
// ═══════════════════════════════════════════════════════════════════
//
//   pub.dev consumer (icu_kit: ^X.Y.Z):
//     Native: automatic via build hook. Downloads the prebuilt binary.
//             The vendored ICU4X source ships in the pub archive (same
//             model as pdf_manipulator), so compile-from-vendor is the
//             fallback when the download is unavailable (needs the
//             Rust toolchain).
//     Web:    manual `flutter pub run icu_kit:setup`.
//             Downloads the WASM; the JS bindings ship in the package.
//
//   Git tag consumer (ref: vX.Y.Z):
//     Same release binaries; the stamped tag carries the vendor as raw
//     source (submodule de-registered), so source builds work directly.
//
//   Git branch consumer (ref: dev, version 0.0.0):
//     Download skipped. Compiles from vendor source or inits
//     submodules first.
//
//   Contributor (path dependency):
//     Same as branch consumer. Always compiles from source.
//
// ═══════════════════════════════════════════════════════════════════
// STALENESS
// ═══════════════════════════════════════════════════════════════════
//
//   Native: fully automatic. The build re-runs the hook when a tracked
//     dependency changes. New assetHashes → hash mismatch →
//     re-downloads.
//
//   Web: NOT automatic. User must run `setup` after a package update.
//     Hash check detects stale files and re-resolves automatically.
//     Tracked: dart-lang/native#988 (WasmAsset/JsAsset support).
//
// ═══════════════════════════════════════════════════════════════════
// ASSET HASHES
// ═══════════════════════════════════════════════════════════════════
//
//   Flat Map<String, String> keyed by GitHub Release asset name.
//   Generated by the shared whuppi/ci release.sh (--update-tag-hashes)
//   from the GitHub Release API digests.
//
// ═══════════════════════════════════════════════════════════════════
// COMPILE DETAILS (preserved from the pre-waterfall hook)
// ═══════════════════════════════════════════════════════════════════
//
//   The compiled library is registered as a CodeAsset under the asset
//   name `src/runtime/native/bindings/lib.g.dart` — the Diplomat-generated
//   `@ffi.Native` annotations resolve symbols against it.
//
//   Cargo's intermediate `target/` lives in `outputDirectoryShared` so
//   the vendored submodule's working tree stays clean and incremental
//   caches survive across hook invocations.
//
//   Rebuild detection (contributors only): every *.rs, *.rs.data (baked
//   data include), and Cargo.toml under the tracked vendor dirs is a
//   dependency, plus the workspace configs (Cargo.toml/.lock,
//   rust-toolchain, .cargo/config, capi build.rs), the bindings barrel,
//   build.json, asset_hashes.dart, pubspec.yaml, and this hook.

import 'dart:convert';
import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;

import 'package:icu_kit/src/hook/asset_hashes.dart';
import 'package:icu_kit/src/hook/resolver.dart';

final _log = Logger('icu_kit:build');

/// The Dart asset path corresponding to our generated bindings library.
/// Diplomat's generated `@ffi.Native` symbols resolve against this asset.
/// Bindings live at lib/src/runtime/native/bindings/ — regenerated by
/// tool/regen_bindings.dart.
const _bindingsAssetName = 'src/runtime/native/bindings/lib.g.dart';

/// Subdirectories of the vendored ICU4X submodule tracked as build
/// dependencies. Any file change under these paths triggers a rebuild
/// via `package:hooks` content-hash comparison.
const _trackedRustDirs = ['components', 'utils', 'provider', 'ffi/capi'];

// ── build.json — single source of truth for all build constants ──
// Loaded once per hook invocation. Every constant that's shared with
// tool/compile_rust.sh and the release pipeline lives here.
Map<String, dynamic>? _buildConfig;
late String _crateName;
late String _repo;
late String _pinnedNightly;
late Map<String, String> _webAssets;
late Map<String, String> _webAssetsLean;
late Set<String> _wasmBuildOutputs;
late String _nativeFeatures;
late String _nativeLeanFeatures;

void _loadBuildConfig(Uri packageRoot) {
  if (_buildConfig != null) return;
  final file = File.fromUri(packageRoot.resolve('build.json'));
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  _buildConfig = json;
  _crateName = json['crate'] as String;
  _repo = json['repo'] as String;
  _pinnedNightly = json['nightlyToolchain'] as String;
  _webAssets = Map<String, String>.from(json['web'] as Map);
  _webAssetsLean = Map<String, String>.from(json['webLean'] as Map);
  _wasmBuildOutputs = Set<String>.from(json['wasmBuildOutputs'] as List);
  final features = json['features'] as Map;
  _nativeFeatures = features['native'] as String;
  _nativeLeanFeatures = features['nativeLean'] as String;
}

String _downloadUrl(String version, String assetName) =>
    'https://github.com/$_repo/releases/download/v$version/$assetName';

// ══════════════════════════════════════════════════════════════════
// § 1 — Hook entry point (native only)
//
// Called automatically for iOS, Android, macOS, Linux, Windows.
// NOT called for web — web goes through resolveWeb() via setup.dart.
// ══════════════════════════════════════════════════════════════════

void main(List<String> args) async {
  await build(args, (BuildInput input, BuildOutputBuilder output) async {
    if (!input.config.buildCodeAssets) return;

    _loadBuildConfig(input.packageRoot);

    final packageRoot = input.packageRoot;
    final bindingsBarrel = packageRoot.resolve(
      'lib/src/runtime/native/bindings/lib.g.dart',
    );
    _verifyBindings(bindingsBarrel);

    final codeConfig = input.config.code;
    final rustTarget = _toRustTarget(codeConfig);
    final linkMode = _linkMode(codeConfig);
    final libFileName = codeConfig.targetOS.libraryFileName(
      _crateName,
      linkMode,
    );
    final lean = !_bundleCldr(input);
    final outFile = File.fromUri(input.outputDirectory.resolve(libFileName));

    // ── Resolve the binary (cache, download, or compile) ──
    await _resolveNative(
      input: input,
      version: readVersion(packageRoot),
      assetName: '${_assetKey(codeConfig, lean: lean)}-$libFileName',
      dest: outFile,
      cacheFile: File.fromUri(
        input.outputDirectoryShared.resolve(
          'prebuilt/$rustTarget${lean ? '-lean' : ''}/$libFileName',
        ),
      ),
      linkMode: linkMode,
    );

    // ── Register with the build ──
    output.assets.code.add(
      CodeAsset(
        package: input.packageName,
        name: _bindingsAssetName,
        linkMode: linkMode,
        file: outFile.uri,
      ),
      routing: input.config.linkingEnabled
          ? ToLinkHook(input.packageName)
          : const ToAppBundle(),
    );

    _trackDependencies(
      output: output,
      packageRoot: packageRoot,
      bindingsBarrel: bindingsBarrel,
    );
  });
}

// ══════════════════════════════════════════════════════════════════
// § 2 — Resolution
// ══════════════════════════════════════════════════════════════════

// ── Native (private) ─────────────────────────────────────────────
// Not public because the correct cache path, target triple, link
// mode, and NDK config all come from the hook's BuildInput — which
// only exists inside the hook. Calling from outside writes to the
// wrong cache. setup <native> delegates to `flutter build` instead.
Future<void> _resolveNative({
  required BuildInput input,
  required String version,
  required String assetName,
  required File dest,
  required File cacheFile,
  required LinkMode linkMode,
}) async {
  await resolveAsset(
    ResolveRequest(
      assetName: assetName,
      downloadUrl: _downloadUrl(version, assetName),
      dest: dest,
      cacheFile: cacheFile,
      expectedHash: assetHashes[assetName],
      version: version,
      packageRoot: input.packageRoot,
      compile: (File d) => _compileIcuCapi(input, linkMode, d),
    ),
  );
}

// ── Web (public — called by bin/setup.dart) ──────────────────────
// Resolves the WASM binary into destDir (typically web/icu_kit/) via
// the waterfall, then copies the COMMITTED web assets — the Diplomat
// JS bindings tree (lib/, ~370 .mjs files) and diplomat.config.mjs —
// straight from the package. Those ship in the pub archive like any
// Dart source (per-file release assets would be absurd at that count),
// so their integrity rides the same trust as the package itself; only
// the gitignored WASM build artifact needs the download waterfall.
//
// Returns the number of files freshly resolved (0 = all cached).
//
// [lean] installs the no-CLDR wasm variant UNDER THE SAME local name
// (icu4x.wasm) — the runtime flavor probe detects which variant loaded,
// so nothing else (config, module URLs, bindings) changes. Switching
// variants later just re-runs setup; the hash check sees the mismatch
// against the other variant's hash and re-resolves.
Future<int> resolveWeb({
  required Uri packageRoot,
  required String version,
  required Directory destDir,
  bool force = false,
  bool lean = false,
}) async {
  _loadBuildConfig(packageRoot);

  if (!destDir.existsSync()) {
    destDir.createSync(recursive: true);
  }

  var installed = 0;

  for (final entry in (lean ? _webAssetsLean : _webAssets).entries) {
    final localName = entry.key;
    final assetName = entry.value;
    final dest = File(p.join(destDir.path, localName));

    assert(
      _wasmBuildOutputs.contains(_sourceArtifact(assetName)),
      'non-wasm web map entries need a copy fallback (see pdf_manipulator)',
    );

    final fresh = await resolveAsset(
      ResolveRequest(
        assetName: assetName,
        downloadUrl: _downloadUrl(version, assetName),
        dest: dest,
        expectedHash: assetHashes[assetName],
        version: version,
        packageRoot: packageRoot,
        force: force,
        compile: (File d) =>
            _compileWasm(packageRoot, d, assetName: assetName, lean: lean),
      ),
    );

    if (fresh) installed++;
  }

  installed += _copyCommittedWebAssets(packageRoot, destDir, force: force);
  return installed;
}

/// Copy the committed (non-WASM) web assets from the package's
/// web_assets/ into [destDir]: `diplomat.config.mjs` + the `lib/`
/// bindings tree. Overwrites when [force] or when the source is newer.
int _copyCommittedWebAssets(
  Uri packageRoot,
  Directory destDir, {
  required bool force,
}) {
  final webAssets = Directory.fromUri(packageRoot.resolve('web_assets/'));
  if (!webAssets.existsSync()) {
    throw StateError(
      'web_assets/ missing from the icu_kit package at $webAssets — '
      'the install is broken; reinstall the package.',
    );
  }

  var copied = 0;
  for (final entity in webAssets.listSync(recursive: true)) {
    if (entity is! File) continue;
    final rel = p.relative(entity.path, from: webAssets.path);
    // Waterfall-owned build artifacts (both wasm variants) — never
    // copied as committed assets, even when a contributor checkout has
    // them built locally.
    if (_wasmBuildOutputs.contains(rel)) continue;
    final dest = File(p.join(destDir.path, rel));
    if (!force &&
        dest.existsSync() &&
        !entity.lastModifiedSync().isAfter(dest.lastModifiedSync())) {
      continue;
    }
    dest.parent.createSync(recursive: true);
    entity.copySync(dest.path);
    copied++;
  }
  return copied;
}

// ══════════════════════════════════════════════════════════════════
// § 3 — Compile callbacks
// ══════════════════════════════════════════════════════════════════

// ── Native: cargo build of the vendored icu_capi ─────────────────

/// Compiles `icu_capi` from `vendor/icu4x` straight to [dest].
///
/// Static builds (iOS's link-mode preference) and no_std targets use the
/// pinned nightly with -Zbuild-std, mirroring upstream ICU4X's own
/// build.sh; everything else builds a cdylib on stable.
Future<void> _compileIcuCapi(
  BuildInput input,
  LinkMode linkMode,
  File dest,
) async {
  final submodule = input.packageRoot.resolve('vendor/icu4x/');
  final rustTarget = _toRustTarget(input.config.code);
  final isNoStd = _noStdTargets.contains(rustTarget);
  final buildStatic = linkMode is StaticLinking;
  final out = dest.uri;

  // Cargo's target dir lives in outputDirectoryShared so:
  //   1. The vendored submodule's working tree stays clean.
  //   2. Incremental cargo cache survives across hook invocations.
  //   3. Different consumer apps share the same cache.
  final cargoTargetDir = input.outputDirectoryShared
      .resolve('cargo-target/')
      .toFilePath();
  final cargoEnv = {
    'CARGO_TARGET_DIR': cargoTargetDir,
    if (isNoStd) 'RUSTFLAGS': '-Zunstable-options -Cpanic=immediate-abort',
  };

  // Android: point cargo at the NDK clang driver Flutter provides. Without
  // this cargo links Android targets with the HOST `cc` (mingw ld / host
  // clang), which rejects the ELF flags and produces host-linked objects.
  if (input.config.code.targetOS == OS.android) {
    final cc = input.config.code.cCompiler;
    if (cc != null) {
      final compilerDir = p.dirname(p.fromUri(cc.compiler));
      final ndkTriple = rustTarget == 'armv7-linux-androideabi'
          ? 'armv7a-linux-androideabi'
          : rustTarget;
      // The NDK per-API clang driver is a `.cmd` batch wrapper on Windows
      // hosts (e.g. aarch64-linux-android21-clang.cmd); passing the bare name
      // makes cargo fail with "could not exec the linker ... program not
      // found". Append the host executable extension so Android cross-compiles
      // link from a Windows host as well as Linux/macOS. Platform.isWindows
      // here is the BUILD host (which runs cargo), not the Android target.
      final clangExt = Platform.isWindows ? '.cmd' : '';
      final envKey =
          'CARGO_TARGET_${rustTarget.toUpperCase().replaceAll('-', '_')}';
      cargoEnv['${envKey}_LINKER'] = p.join(
        compilerDir,
        '${ndkTriple}21-clang$clangExt',
      );
      cargoEnv['${envKey}_AR'] = p.join(compilerDir, 'llvm-ar');
      _log.info('NDK linker: ${cargoEnv['${envKey}_LINKER']}');
    }
  }

  final workdir = Directory.fromUri(submodule);
  final crateType = buildStatic ? 'staticlib' : 'cdylib';

  _log.info(
    'building icu_capi for $rustTarget '
    '($crateType, ${isNoStd ? 'no_std nightly' : 'std stable'})',
  );

  if (buildStatic || isNoStd) {
    await _run('rustup', [
      'toolchain',
      'install',
      '--no-self-update',
      _pinnedNightly,
      '--component',
      'rust-src',
    ], workdir);
  }

  await _run('rustup', [
    'target',
    'add',
    rustTarget,
    if (buildStatic || isNoStd) ...['--toolchain', _pinnedNightly],
  ], workdir);

  final addedFeatures = isNoStd
      ? const ['libc_alloc', 'looping_panic_handler']
      : const ['simple_logger'];
  final allFeatures = _resolveCargoFeatures(input, addedFeatures).join(',');

  await _run(
    'cargo',
    [
      if (buildStatic || isNoStd) '+$_pinnedNightly',
      'rustc',
      '--manifest-path=ffi/capi/Cargo.toml',
      '--crate-type=$crateType',
      '--release',
      '--config=profile.release.panic="abort"',
      '--config=profile.release.codegen-units=1',
      '--no-default-features',
      '--features=$allFeatures',
      if (isNoStd) '-Zbuild-std=core,alloc',
      if (buildStatic || isNoStd) ...['-Zbuild-std=std,panic_abort'],
      '--target=$rustTarget',
      '--',
      '--emit',
      'link=${out.toFilePath(windows: Platform.isWindows)}',
    ],
    workdir,
    environment: cargoEnv,
  );

  if (!dest.existsSync()) {
    throw StateError(
      'cargo claimed success but output missing at $out. '
      'Inspect logs above for cargo warnings.',
    );
  }

  _log.info('compiled: ${out.toFilePath()}');
}

// ── Web: the WASM binary ─────────────────────────────────────────

/// The web_assets/ artifact behind a release asset name. Release assets
/// carry the `wasm-` flatten prefix the pipeline adds to files from the
/// wasm build's output dir; stripping it recovers the on-disk name
/// (`wasm-icu4x-lean.wasm` → `icu4x-lean.wasm`).
String _sourceArtifact(String assetName) =>
    assetName.startsWith('wasm-') ? assetName.substring(5) : assetName;

Future<void> _compileWasm(
  Uri packageRoot,
  File dest, {
  required String assetName,
  required bool lean,
}) async {
  final sourceName = _sourceArtifact(assetName);
  final existing = File.fromUri(packageRoot.resolve('web_assets/$sourceName'));

  // Contributor has locally built WASM — copy directly.
  if (existing.existsSync()) {
    dest.parent.createSync(recursive: true);
    existing.copySync(dest.path);
    return;
  }

  // Compile from source (nightly Rust; the tool self-provisions).
  final script = File.fromUri(packageRoot.resolve('tool/build_wasm.dart'));
  if (!script.existsSync()) {
    throw StateError(
      'tool/build_wasm.dart not found. Cannot compile WASM.\n'
      'Install from pub.dev or use a git tag with pre-built binaries.',
    );
  }

  final result = await Process.run('dart', [
    'run',
    'tool/build_wasm.dart',
    if (lean) '--lean',
  ], workingDirectory: p.fromUri(packageRoot));
  if (result.exitCode != 0) {
    throw StateError(
      'WASM compilation failed (exit ${result.exitCode}).\n'
      'stderr: ${result.stderr}\n\n'
      'Ensure Rust is installed: https://rustup.rs',
    );
  }

  if (!existing.existsSync()) {
    throw StateError(
      'WASM compiled but $sourceName not found at ${existing.path}',
    );
  }
  dest.parent.createSync(recursive: true);
  existing.copySync(dest.path);
}

// ══════════════════════════════════════════════════════════════════
// § 4 — Dependencies + verification
// ══════════════════════════════════════════════════════════════════

/// Throws with an actionable error if the bindings haven't been generated.
void _verifyBindings(Uri bindingsBarrel) {
  if (!File.fromUri(bindingsBarrel).existsSync()) {
    throw StateError(
      'Diplomat-generated bindings not found at $bindingsBarrel.\n'
      'Run: fvm dart run tool/regen_bindings.dart',
    );
  }
}

/// Register every file `package:hooks` should hash to decide whether the
/// hook needs to re-run. Must over-approximate cargo's inputs and must
/// exist BEFORE the first build — never derive this list from build
/// outputs, or caching goes circular and binaries go stale.
///
/// The vendor walk only runs when the vendor source is on disk. It
/// always is for pub installs (the vendor ships in the tarball); it's
/// absent only on a git clone without `--recursive`.
void _trackDependencies({
  required BuildOutputBuilder output,
  required Uri packageRoot,
  required Uri bindingsBarrel,
}) {
  output.dependencies.addAll([
    bindingsBarrel,
    packageRoot.resolve('pubspec.yaml'),
    packageRoot.resolve('build.json'),
    packageRoot.resolve('hook/build.dart'),
    packageRoot.resolve('lib/src/hook/asset_hashes.dart'),
    packageRoot.resolve('lib/src/hook/resolver.dart'),
  ]);

  if (!hasVendorSource(packageRoot)) return;

  final submodule = packageRoot.resolve('vendor/icu4x/');
  // Workspace + crate configs: feature edits, toolchain bumps, and linker
  // flags change the binary without touching any .rs file.
  const configs = [
    'Cargo.toml',
    'Cargo.lock',
    'rust-toolchain.toml',
    'rust-toolchain',
    '.cargo/config.toml',
    '.cargo/config',
    'ffi/capi/Cargo.toml',
    'ffi/capi/build.rs',
  ];
  for (final file in configs) {
    final uri = submodule.resolve(file);
    if (File.fromUri(uri).existsSync()) {
      output.dependencies.add(uri);
    }
  }
  for (final dirName in _trackedRustDirs) {
    final dir = Directory.fromUri(submodule.resolve('$dirName/'));
    if (!dir.existsSync()) continue;
    for (final entity in dir.listSync(recursive: true, followLinks: false)) {
      // What cargo actually reads: sources, baked-data includes, and
      // per-crate manifests. NOT every file — provider/source/ alone is
      // 7k+ files of datagen-only CLDR input that cargo never touches,
      // and package:hooks content-hashes every dependency per run.
      if (entity is File &&
          (entity.path.endsWith('.rs') ||
              entity.path.endsWith('.rs.data') ||
              entity.path.endsWith('Cargo.toml'))) {
        output.dependencies.add(entity.uri);
      }
    }
  }
}

// ══════════════════════════════════════════════════════════════════
// § 5 — CodeConfig mapping
// ══════════════════════════════════════════════════════════════════

/// Whether this build bakes the CLDR in. Reads the `bundleCldrData`
/// user_define from the consumer's pubspec:
///
/// ```yaml
/// hooks:
///   user_defines:
///     icu_kit:
///       bundleCldrData: false   # lean binary; use IcuData.lazy at runtime
/// ```
///
/// Default is `true` — full CLDR baked in. Set to `false` for the lean
/// binary without the ~19 MB CLDR statics; apps must then init with
/// `IcuData.lazy(...)` to load per-locale postcards on demand.
bool _bundleCldr(BuildInput input) {
  final raw = input.userDefines['bundleCldrData'];
  return switch (raw) {
    null => true,
    final bool b => b,
    'true' || 'True' => true,
    'false' || 'False' => false,
    _ => throw ArgumentError('''
icu_kit user_define `bundleCldrData` must be a bool, got: $raw

Set it in your app's pubspec.yaml:

* Fat binary (default) — full CLDR baked in, works offline out of the box:
```
hooks:
  user_defines:
    icu_kit:
      bundleCldrData: true
```

* Lean binary — no CLDR statics (~19 MB smaller); the app must init with
  `IcuData.lazy(...)` and load per-locale postcards at runtime:
```
hooks:
  user_defines:
    icu_kit:
      bundleCldrData: false
```
'''),
  };
}

/// Resolve the full cargo feature list for this build from build.json's
/// `native` / `nativeLean` sets (the single source of truth shared with
/// tool/compile_rust.sh and the S7 analyze gate), plus per-target
/// additions.
List<String> _resolveCargoFeatures(BuildInput input, List<String> added) {
  final bundleCldr = _bundleCldr(input);
  _log.info(
    'cldr bundling: ${bundleCldr ? 'ON (compiled_data)' : 'OFF (lazy only)'}',
  );
  return [
    ...(bundleCldr ? _nativeFeatures : _nativeLeanFeatures).split(','),
    ...added,
  ];
}

/// Rust targets that require `-Zbuild-std` and a no_std-friendly feature
/// set. ICU4X's own build.sh treats these specially.
const _noStdTargets = <String>{
  'riscv64-linux-android',
  'riscv64gc-unknown-linux-gnu',
  'wasm32-unknown-unknown',
};

/// The link mode this build wants, straight from the preference. iOS
/// builds prefer static (a staticlib lands in the app binary); every
/// other Flutter target prefers dynamic. Never force static merely
/// because linking is enabled — release/AOT builds route the SAME
/// dynamic asset through the passthrough link hook.
LinkMode _linkMode(CodeConfig code) {
  return switch (code.linkModePreference) {
    LinkModePreference.dynamic ||
    LinkModePreference.preferDynamic => DynamicLoadingBundled(),
    LinkModePreference.static ||
    LinkModePreference.preferStatic => StaticLinking(),
    _ => DynamicLoadingBundled(),
  };
}

/// Map Dart's `(targetOS, targetArchitecture)` to Cargo's Rust target triple.
String _toRustTarget(CodeConfig code) {
  if (code.targetOS == OS.iOS &&
      code.targetArchitecture == Architecture.arm64 &&
      code.iOS.targetSdk == IOSSdk.iPhoneSimulator) {
    return 'aarch64-apple-ios-sim';
  }
  return switch ((code.targetOS, code.targetArchitecture)) {
    (OS.android, Architecture.arm) => 'armv7-linux-androideabi',
    (OS.android, Architecture.arm64) => 'aarch64-linux-android',
    (OS.android, Architecture.ia32) => 'i686-linux-android',
    (OS.android, Architecture.x64) => 'x86_64-linux-android',
    (OS.iOS, Architecture.arm64) => 'aarch64-apple-ios',
    (OS.iOS, Architecture.x64) => 'x86_64-apple-ios',
    (OS.linux, Architecture.arm) => 'armv7-unknown-linux-gnueabihf',
    (OS.linux, Architecture.arm64) => 'aarch64-unknown-linux-gnu',
    (OS.linux, Architecture.x64) => 'x86_64-unknown-linux-gnu',
    (OS.macOS, Architecture.arm64) => 'aarch64-apple-darwin',
    (OS.macOS, Architecture.x64) => 'x86_64-apple-darwin',
    (OS.windows, Architecture.arm64) => 'aarch64-pc-windows-msvc',
    (OS.windows, Architecture.x64) => 'x86_64-pc-windows-msvc',
    (_, _) => throw UnimplementedError(
      'icu_kit: no Rust target mapping for '
      '${code.targetOS} ${code.targetArchitecture}',
    ),
  };
}

/// Release-asset key for this config: the target key, plus `-lean` when
/// the CLDR is not bundled. Combined with the platform library filename
/// it names the GitHub Release asset (e.g.
/// `macos-arm64-libicu_capi.dylib`, `android-arm64-lean-libicu_capi.so`).
/// tool/compile_rust.sh writes its outputs under these same keys.
String _assetKey(CodeConfig code, {required bool lean}) {
  final base = _targetKey(code);
  return lean ? '$base-lean' : base;
}

String _targetKey(CodeConfig code) {
  if (code.targetOS == OS.iOS &&
      code.targetArchitecture == Architecture.arm64 &&
      code.iOS.targetSdk == IOSSdk.iPhoneSimulator) {
    return 'ios-sim-arm64';
  }
  return switch ((code.targetOS, code.targetArchitecture)) {
    (OS.android, Architecture.arm) => 'android-arm',
    (OS.android, Architecture.arm64) => 'android-arm64',
    (OS.android, Architecture.ia32) => 'android-x86',
    (OS.android, Architecture.x64) => 'android-x64',
    (OS.iOS, Architecture.arm64) => 'ios-arm64',
    (OS.iOS, Architecture.x64) => 'ios-sim-x64',
    (OS.linux, Architecture.arm) => 'linux-arm',
    (OS.linux, Architecture.arm64) => 'linux-arm64',
    (OS.linux, Architecture.x64) => 'linux-x64',
    (OS.macOS, Architecture.arm64) => 'macos-arm64',
    (OS.macOS, Architecture.x64) => 'macos-x64',
    (OS.windows, Architecture.arm64) => 'windows-arm64',
    (OS.windows, Architecture.x64) => 'windows-x64',
    (_, _) => throw UnsupportedError(
      'Unsupported: ${code.targetOS} ${code.targetArchitecture}',
    ),
  };
}

/// Run an external process with stdout/stderr streamed live, so cargo's
/// own progress + warnings show up under `flutter run` in real time
/// instead of buffering until completion.
Future<void> _run(
  String exe,
  List<String> args,
  Directory cwd, {
  Map<String, String>? environment,
}) async {
  _log.fine('  \$ $exe ${args.join(' ')}');
  final process = await Process.start(
    exe,
    args,
    workingDirectory: cwd.path,
    environment: environment,
    mode: ProcessStartMode.inheritStdio,
  );
  final code = await process.exitCode;
  if (code != 0) {
    throw ProcessException(exe, args, 'exit $code', code);
  }
}
