// generated by diplomat-tool
import { CurrencyWidth } from "./CurrencyWidth.mjs"
import { DataError } from "./DataError.mjs"
import { DataProvider } from "./DataProvider.mjs"
import { Decimal } from "./Decimal.mjs"
import { Locale } from "./Locale.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const CurrencyFormatter_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.icu4x_CurrencyFormatter_destroy_mv1(ptr);
});

/**
 * An ICU4X currency formatter object that renders a {@link Decimal} with a
 * short or narrow currency symbol (e.g. "$1.00" or "US$1").
 *
 * For long-form ("1 US dollar") use {@link LongCurrencyFormatter}.
 *
 * See the [Rust documentation for `CurrencyFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html) for more information.
 */
export class CurrencyFormatter {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("CurrencyFormatter is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            CurrencyFormatter_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new {@link CurrencyFormatter} using compiled CLDR data.
     *
     * Returns an error if the locale has no currency data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html#method.try_new) for more information.
     */
    static createWithWidth(locale, width) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_CurrencyFormatter_create_with_width_mv1(diplomatReceive.buffer, locale.ffiValue, diplomatRuntime.optionToBufferForCalling(wasm, width, 4, 4, functionCleanupArena, (arrayBuffer, offset, jsValue) => [diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, jsValue.ffiValue, Int32Array)]));

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DataError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('DataError.' + cause.value, { cause });
            }
            return new CurrencyFormatter(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    static createWithWidthWithProvider(provider, locale, width) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_CurrencyFormatter_create_with_width_with_provider_mv1(diplomatReceive.buffer, provider.ffiValue, locale.ffiValue, diplomatRuntime.optionToBufferForCalling(wasm, width, 4, 4, functionCleanupArena, (arrayBuffer, offset, jsValue) => [diplomatRuntime.writeToArrayBuffer(arrayBuffer, offset + 0, jsValue.ffiValue, Int32Array)]));

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DataError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('DataError.' + cause.value, { cause });
            }
            return new CurrencyFormatter(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Format `value` with `currency_code` (3-letter ISO 4217, e.g. "USD").
     *
     * Returns an empty string if `currency_code` is not a valid 3-letter
     * ASCII code; callers should validate first.
     *
     * See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html#method.format_fixed_decimal) for more information.
     */
    format(value, currencyCode) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const currencyCodeSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, currencyCode)));
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.icu4x_CurrencyFormatter_format_mv1(this.ffiValue, value.ffiValue, currencyCodeSlice.ptr, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            write.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}