// generated by diplomat-tool
import type { CurrencyWidth } from "./CurrencyWidth"
import type { DataError } from "./DataError"
import type { DataProvider } from "./DataProvider"
import type { Decimal } from "./Decimal"
import type { Locale } from "./Locale"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * An ICU4X currency formatter object that renders a {@link Decimal} with a
 * short or narrow currency symbol (e.g. "$1.00" or "US$1").
 *
 * For long-form ("1 US dollar") use {@link LongCurrencyFormatter}.
 *
 * See the [Rust documentation for `CurrencyFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html) for more information.
 */
export class CurrencyFormatter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new {@link CurrencyFormatter} using compiled CLDR data.
     *
     * Returns an error if the locale has no currency data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html#method.try_new) for more information.
     */
    static createWithWidth(locale: Locale, width: CurrencyWidth | null): CurrencyFormatter;

    static createWithWidthWithProvider(provider: DataProvider, locale: Locale, width: CurrencyWidth | null): CurrencyFormatter;

    /**
     * Format `value` with `currency_code` (3-letter ISO 4217, e.g. "USD").
     *
     * Returns an empty string if `currency_code` is not a valid 3-letter
     * ASCII code; callers should validate first.
     *
     * See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/formatter/struct.CurrencyFormatter.html#method.format_fixed_decimal) for more information.
     */
    format(value: Decimal, currencyCode: string): string;
}