// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Width controlling the symbol form for {@link CurrencyFormatter}.
 * Mirrors `icu_experimental::dimension::currency::options::Width`.
 *
 * See the [Rust documentation for `Width`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/options/enum.Width.html) for more information.
 */
export class CurrencyWidth {

    /** @internal */
    static fromValue(value: CurrencyWidth | string): CurrencyWidth;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    static Short : CurrencyWidth;
    static Narrow : CurrencyWidth;
    /**
     * ISO 4217 code display (e.g. "USD 1.00"). icu_kit fork addition for
     * ECMA-402 `currencyDisplay: "code"`.
     */
    static Code : CurrencyWidth;


    constructor(value: CurrencyWidth | string );
}