// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Width controlling the symbol form for {@link CurrencyFormatter}.
 * Mirrors `icu_experimental::dimension::currency::options::Width`.
 *
 * See the [Rust documentation for `Width`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/options/enum.Width.html) for more information.
 */
export class CurrencyWidth {
    #value = undefined;

    static #values = new Map([
        ["Short", 0],
        ["Narrow", 1],
        ["Code", 2]
    ]);

    static getAllEntries() {
        return CurrencyWidth.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return CurrencyWidth.#objectValues[arguments[1]];
        }

        if (value instanceof CurrencyWidth) {
            return value;
        }

        let intVal = CurrencyWidth.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return CurrencyWidth.#objectValues[intVal];
        }

        throw TypeError(value + " is not a CurrencyWidth and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new CurrencyWidth(value);
    }

    get value(){
        return [...CurrencyWidth.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new CurrencyWidth(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new CurrencyWidth(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new CurrencyWidth(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
    ];

    static Short = CurrencyWidth.#objectValues[0];
    static Narrow = CurrencyWidth.#objectValues[1];
    /**
     * ISO 4217 code display (e.g. "USD 1.00"). icu_kit fork addition for
     * ECMA-402 `currencyDisplay: "code"`.
     */
    static Code = CurrencyWidth.#objectValues[2];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}