// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * A formatted number decomposed into typed parts, mirroring ECMA-402
 * `Intl.NumberFormat.prototype.formatToParts`.
 *
 * Each part is a `(type, value)` pair; the types are the ECMA-402 names
 * (`"integer"`, `"group"`, `"decimal"`, `"fraction"`, `"minusSign"`,
 * `"plusSign"`, `"percentSign"`, `"currency"`, `"unit"`, `"literal"`, …).
 * Concatenating every part's value reproduces the flat formatted string.
 */
export class FormattedNumberParts {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * The number of parts.
     */
    get partCount(): number;

    /**
     * The ECMA-402 type name of the part at `index`, or nothing if the
     * index is out of bounds.
     */
    partTypeAt(index: number): string | null;

    /**
     * The substring of the part at `index`, or nothing if the index is
     * out of bounds.
     */
    partValueAt(index: number): string | null;
}