// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Errors that can occur during IDNA processing.
 *
 * `Invalid` covers all UTS #46 / RFC 5891 validation failures —
 * the `idna` crate aggregates many specific errors into a single
 * `Errors` opaque type, so we collapse them here for the FFI surface.
 */
export class IdnaError {
    #value = undefined;

    static #values = new Map([
        ["Unknown", 0],
        ["InvalidUtf8", 1],
        ["Invalid", 2]
    ]);

    static getAllEntries() {
        return IdnaError.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return IdnaError.#objectValues[arguments[1]];
        }

        if (value instanceof IdnaError) {
            return value;
        }

        let intVal = IdnaError.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return IdnaError.#objectValues[intVal];
        }

        throw TypeError(value + " is not a IdnaError and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new IdnaError(value);
    }

    get value(){
        return [...IdnaError.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new IdnaError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new IdnaError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new IdnaError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
    ];

    static Unknown = IdnaError.#objectValues[0];
    static InvalidUtf8 = IdnaError.#objectValues[1];
    static Invalid = IdnaError.#objectValues[2];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}