// generated by diplomat-tool
import type { DataError } from "./DataError"
import type { DataProvider } from "./DataProvider"
import type { Decimal } from "./Decimal"
import type { DecimalGroupingStrategy } from "./DecimalGroupingStrategy"
import type { FormattedNumberParts } from "./FormattedNumberParts"
import type { Locale } from "./Locale"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * An ICU4X long-form currency formatter pinned to one currency
 * (e.g. "1 US dollar" / "2 US dollars" with locale-aware plural form).
 *
 * See the [Rust documentation for `LongCurrencyFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html) for more information.
 */
export class LongCurrencyFormatter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new {@link LongCurrencyFormatter} for one currency using
     * compiled CLDR data.
     *
     * Returns `Err(DataError)` if the locale or currency has no data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html#method.try_new) for more information.
     */
    static createForCurrency(locale: Locale, currencyCode: string, groupingStrategy: DecimalGroupingStrategy | null): LongCurrencyFormatter;

    static createForCurrencyWithProvider(provider: DataProvider, locale: Locale, currencyCode: string, groupingStrategy: DecimalGroupingStrategy | null): LongCurrencyFormatter;

    /**
     * Format `value` using the locale-specific plural form
     * (e.g. "1 US dollar" / "2 US dollars").
     *
     * See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html#method.format_fixed_decimal) for more information.
     */
    format(value: Decimal): string;

    /**
     * Format `value` into typed parts (ECMA-402 `formatToParts` shape):
     * the long currency name as a single `currency` part, the number as
     * integer / group / decimal / fraction.
     */
    formatToParts(value: Decimal): FormattedNumberParts;
}