// generated by diplomat-tool
import { DataError } from "./DataError.mjs"
import { DataProvider } from "./DataProvider.mjs"
import { Decimal } from "./Decimal.mjs"
import { FormattedNumberParts } from "./FormattedNumberParts.mjs"
import { Locale } from "./Locale.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const LongCurrencyFormatter_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.icu4x_LongCurrencyFormatter_destroy_mv1(ptr);
});

/**
 * An ICU4X long-form currency formatter pinned to one currency
 * (e.g. "1 US dollar" / "2 US dollars" with locale-aware plural form).
 *
 * See the [Rust documentation for `LongCurrencyFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html) for more information.
 */
export class LongCurrencyFormatter {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("LongCurrencyFormatter is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            LongCurrencyFormatter_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new {@link LongCurrencyFormatter} for one currency using
     * compiled CLDR data.
     *
     * Returns `Err(DataError)` if the locale or currency has no data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html#method.try_new) for more information.
     */
    static createForCurrency(locale, currencyCode) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const currencyCodeSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, currencyCode)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_LongCurrencyFormatter_create_for_currency_mv1(diplomatReceive.buffer, locale.ffiValue, currencyCodeSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DataError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('DataError.' + cause.value, { cause });
            }
            return new LongCurrencyFormatter(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    static createForCurrencyWithProvider(provider, locale, currencyCode) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const currencyCodeSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, currencyCode)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_LongCurrencyFormatter_create_for_currency_with_provider_mv1(diplomatReceive.buffer, provider.ffiValue, locale.ffiValue, currencyCodeSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new DataError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('DataError.' + cause.value, { cause });
            }
            return new LongCurrencyFormatter(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Format `value` using the locale-specific plural form
     * (e.g. "1 US dollar" / "2 US dollars").
     *
     * See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/currency/long_formatter/struct.LongCurrencyFormatter.html#method.format_fixed_decimal) for more information.
     */
    format(value) {
        const write = new diplomatRuntime.DiplomatWriteBuf(wasm);

    wasm.icu4x_LongCurrencyFormatter_format_mv1(this.ffiValue, value.ffiValue, write.buffer);

        try {
            return write.readString8();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            write.free();
        }
    }

    /**
     * Format `value` into typed parts (ECMA-402 `formatToParts` shape):
     * the long currency name as a single `currency` part, the number as
     * integer / group / decimal / fraction.
     */
    formatToParts(value) {

        const result = wasm.icu4x_LongCurrencyFormatter_format_to_parts_mv1(this.ffiValue, value.ffiValue);

        try {
            return new FormattedNumberParts(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}