// generated by diplomat-tool
import type { DataError } from "./DataError"
import type { DataProvider } from "./DataProvider"
import type { Decimal } from "./Decimal"
import type { Locale } from "./Locale"
import type { PercentDisplay } from "./PercentDisplay"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * An ICU4X percent formatter object that renders a {@link Decimal} with the
 * locale's percent sign (e.g. "12.34%" in en-US, "12,34 %" in fr).
 *
 * See the [Rust documentation for `PercentFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/percent/formatter/struct.PercentFormatter.html) for more information.
 */
export class PercentFormatter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new {@link PercentFormatter} using compiled CLDR data.
     *
     * Returns an error if the locale has no percent data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/percent/formatter/struct.PercentFormatter.html#method.try_new) for more information.
     */
    static createWithDisplay(locale: Locale, display: PercentDisplay | null): PercentFormatter;

    static createWithDisplayWithProvider(provider: DataProvider, locale: Locale, display: PercentDisplay | null): PercentFormatter;

    /**
     * Format `value` as a percent. The decimal is interpreted as already
     * scaled (i.e. `0.12` → "0.12%", not "12%"). Pre-multiply by 100 in
     * Dart if you want ECMA-402 percent semantics ("12%" from `0.12`).
     *
     * See the [Rust documentation for `format`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/percent/formatter/struct.PercentFormatter.html#method.format) for more information.
     */
    format(value: Decimal): string;
}