// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Formatting style for relative times.
 * Mirrors `icu_experimental::relativetime::options::Numeric`.
 *
 * See the [Rust documentation for `Numeric`](https://docs.rs/icu/2.2.0/icu/experimental/relativetime/options/enum.Numeric.html) for more information.
 */
export class RelativeTimeNumeric {
    #value = undefined;

    static #values = new Map([
        ["Always", 0],
        ["Auto", 1]
    ]);

    static getAllEntries() {
        return RelativeTimeNumeric.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return RelativeTimeNumeric.#objectValues[arguments[1]];
        }

        if (value instanceof RelativeTimeNumeric) {
            return value;
        }

        let intVal = RelativeTimeNumeric.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return RelativeTimeNumeric.#objectValues[intVal];
        }

        throw TypeError(value + " is not a RelativeTimeNumeric and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new RelativeTimeNumeric(value);
    }

    get value(){
        return [...RelativeTimeNumeric.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new RelativeTimeNumeric(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new RelativeTimeNumeric(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Always = RelativeTimeNumeric.#objectValues[0];
    static Auto = RelativeTimeNumeric.#objectValues[1];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}