// generated by diplomat-tool
import type { DataError } from "./DataError"
import type { DataProvider } from "./DataProvider"
import type { Decimal } from "./Decimal"
import type { FormattedNumberParts } from "./FormattedNumberParts"
import type { Locale } from "./Locale"
import type { UnitsWidth } from "./UnitsWidth"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * An ICU4X unit formatter pinned to a single CLDR unit identifier
 * (e.g. "meter", "kilometer-per-hour", "hour"). Renders values like
 * "5 hours", "5 hr", "5 h" depending on width.
 *
 * See the [Rust documentation for `UnitsFormatter`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/units/formatter/struct.UnitsFormatter.html) for more information.
 */
export class UnitsFormatter {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new {@link UnitsFormatter} for `unit_identifier` using compiled
     * CLDR data.
     *
     * `unit_identifier` is a CLDR unit identifier (e.g. "meter",
     * "kilometer", "kilometer-per-hour", "hour"). Returns an error if the
     * locale or unit has no data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/units/formatter/struct.UnitsFormatter.html#method.try_new) for more information.
     */
    static createForUnit(locale: Locale, unitIdentifier: string, width: UnitsWidth | null): UnitsFormatter;

    static createForUnitWithProvider(provider: DataProvider, locale: Locale, unitIdentifier: string, width: UnitsWidth | null): UnitsFormatter;

    /**
     * Format `value` with the unit. Returns the locale-correct plural
     * form (e.g. "1 hour" / "2 hours" in en-US).
     *
     * See the [Rust documentation for `format_fixed_decimal`](https://docs.rs/icu/2.2.0/icu/experimental/dimension/units/formatter/struct.UnitsFormatter.html#method.format_fixed_decimal) for more information.
     */
    format(value: Decimal): string;

    /**
     * Format `value` into typed parts (ECMA-402 `formatToParts` shape):
     * integer / group / decimal / fraction, with the unit name as a
     * single `unit` part and surrounding spacing as `literal`.
     */
    formatToParts(value: Decimal): FormattedNumberParts;
}