// The dispatch seam. Native and web dispatch are BOTH generated by
// `tool/regen_dispatch.dart` with IDENTICAL Dart signatures — the native
// twin speaks FFI types, the web twin the js_interop mirrors — so every
// facade calls `dispatch.x(...)` through this one conditional import and
// compiles unchanged on both platforms. Each dispatch method picks the
// compiled-data vs `*WithProvider` constructor per call; facades never
// branch themselves.
export 'native/dispatch.g.dart'
    if (dart.library.js_interop) 'web/dispatch.g.dart';
